name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: open-jdk
    steps:
      - uses: actions/checkout@v2
      - name: Build Project
        run : |
          java -version
          javac - version
          javac src/*.java